feat: Add database routing table support
mozilla-services/autopush-rs pull request #473
Opened 2023-10-17 23:44 UTC by jrconlin

This adds a table to the database stores to route data to the
appropriate storage backend.

Closes: SYNC-3452

2023-12-13 18:38 UTC, jrconlin commented on autopush-common/src/db/dynamodb/mod.rs
> +    pub current_message_month: String,
Ah, good catch. missed those.

2023-12-13 20:37 UTC, pjenvey reviewed
sorry, missed a couple more things

2023-12-13 20:37 UTC, pjenvey commented on Cargo.toml
> +] }
I think this was in another PR as well -- we don't use this feature AFAICT

```suggestion
sentry-core = { version = "0.31" }
```

2023-12-13 20:37 UTC, pjenvey commented on autopush-common/src/db/bigtable/bigtable_client/mod.rs
> +        table_name: Option<String>,
Why the new optional argument? I don't see it being used (`None` is always passed)

2023-12-13 20:55 UTC, jrconlin commented
Yeah, this looks like more merge detritus. (there was a lot.)

2023-12-13 22:09 UTC, pjenvey requested changes

2023-12-13 22:09 UTC, pjenvey commented on autopush-common/src/db/bigtable/bigtable_client/mod.rs
> +        table_name: Option<String>,
There's still this one for `write_row`

2023-12-14 00:28 UTC, pjenvey approved these changes

2023-12-14 03:51 UTC, merged