Document VAPID key should be base64 encoded
mozilla-services/autopush-rs pull request #533
Opened 2023-12-04 21:49 UTC by tarikeshaq

Realized there was no documentation on the format of the VAPID key, read the source code and realized we call https://github.com/mozilla-services/autopush-rs/blob/6624a19ad97af90174cc7623b9b8683392c3aec9/autopush-common/src/util/mod.rs#L30-L32

(for reference, here's where we initiate the decoding while [making the endpoint](https://github.com/mozilla-services/autopush-rs/blob/6624a19ad97af90174cc7623b9b8683392c3aec9/autopush-common/src/endpoint.rs#L26)

cc @jrconlin

2023-12-04 22:14 UTC, jonalmeida approved these changes
Nice!

As mentioned offline, if we want to add some simple checks to avoid common mistakes, we could do something similar to [Gecko's WebPushSubscription construction](https://searchfox.org/mozilla-central/rev/78a2c17cc80680a5a82446e4ce7c45a73b935383/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebPushSubscription.java#96-114).

2023-12-05 00:18 UTC, jrconlin requested changes
Really, just the one change to use the proper RFC.

2023-12-05 00:18 UTC, jrconlin commented on docs/src/http.md
> +_The [VAPID Key](https://datatracker.ietf.org/doc/html/draft-ietf-webpush-vapid-01) provided by the subscribing third party_
It's a real RFC, no need to refer to the draft (particularly a very old draft).

```suggestion
_The [VAPID Key](https://datatracker.ietf.org/doc/html/rfc8292#section-3.2) provided by the subscribing third party_
```

2023-12-05 17:12 UTC, jrconlin approved these changes

2023-12-05 19:25 UTC, tarikeshaq commented
Hmm I've seen this sometimes in the past, lemme try closing and re-opening the PR

2023-12-05 20:20 UTC, jrconlin commented
Rather than fight CI, https://github.com/mozilla-services/autopush-rs/pull/535

2023-12-05 22:21 UTC, closed without merging