Update docs to decrement DynamoDB and use Bigtable
mozilla-services/autopush-rs pull request #677
Opened 2024-04-11 00:23 UTC by jrconlin

Issue: SYNC-3378

2024-04-11 23:47 UTC, pjenvey requested changes

2024-04-11 23:47 UTC, pjenvey commented on docs/src/testing.md
> +cbt -project test -instance test setgcpolicy autopush message_topic maxversions=1 and maxage=1s
```suggestion
scripts/setup_bt.sh
```

2024-04-15 17:31 UTC, pjenvey approved these changes

2024-04-15 18:23 UTC, taddes approved these changes
LGTM 👍

2024-04-16 16:33 UTC, merged