chore: Updates for rust 1.80
mozilla-services/autopush-rs pull request #740
Opened 2024-07-25 16:03 UTC by jrconlin

* Mostly documentation fixes.
* fix broken `cfg!` call
* Add docs for StubRouter

2024-07-25 16:23 UTC, taddes requested changes
Thanks for the update! Just some notes on a lonely `///` and a few missing comments/examples.

2024-07-25 16:23 UTC, taddes commented on autoendpoint/src/routers/stub/settings.rs
> +///
Think we can remove this redundant`///` 
```suggestion
```

2024-07-25 16:23 UTC, taddes commented on autoendpoint/src/routers/stub/router.rs
> +    /// to use by designating the value in the `app_id` of the subscription URL. (e.g.)
Was there supposed to be an example added after the description, hence the ` (e.g.)` ?

2024-07-25 16:23 UTC, taddes commented on autoendpoint/Cargo.toml
> +# The "stub" will return errors and
Is there a missing description after the and that we need here?

2024-07-25 17:15 UTC, jrconlin commented
Sorry, this was meant to be a draft until the docker images for 1.80 land tomorrow.

2024-07-26 22:47 UTC, taddes approved these changes
🚀 Tyty!

2024-07-29 17:04 UTC, merged