Feat: Add urgency support
mozilla-services/autopush-rs pull request #815
Opened 2024-12-30 18:19 UTC by p1gp1g

It allows clients to define the minimum urgency of messages they wish to receive. For example, a client with low battery can request a high urgency message only until their battery is good again.

2025-01-02 19:29 UTC, jrconlin requested changes
Looks interesting, but my major concern is that we're changing the client protocol, and we'd want to make sure that we don't break anything on the current or legacy UA. I'd be more comfortable landing this if it was behind a feature flag so that we could test it in isolation from production or stage. 

Obviously, this change would also require updates to the UA code to actually consume and utilize the new `Urgency` message, and I don't know what priority that might be with that team.

2025-01-02 19:29 UTC, jrconlin commented on autoconnect/autoconnect-common/src/protocol.rs
Introducing new protocol messages should be kept behind a feature flag until we can properly verify that there are no problems with current or legacy UserAgents.

2025-01-02 19:29 UTC, jrconlin commented on autoconnect/autoconnect-common/src/protocol.rs
Introducing new protocol messages should be kept behind a feature flag until we can properly verify that there are no problems with current or legacy UserAgents.

2025-01-02 19:29 UTC, jrconlin commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            let current_urgency = user.urgency.unwrap_or(Urgency::VeryLow);
Wouldn't the default urgency be `Urgency::Normal`?

I presume that any message without an explicit urgency flag would be prioritized over any message that had specified a lower than normal urgency.

2025-01-02 19:29 UTC, jrconlin commented on autopush-common/src/db/mod.rs
> +}
Considering that the two times you're using a `from` here, you might want to consider adding a `impl From<Option<actix_web::http::HeaderValue>> for Urgency`

2025-01-03 08:01 UTC, p1gp1g commented
Thank you for your review, I've introduced a new feature for the urgency and addressed 2 other comments

2025-01-03 08:02 UTC, p1gp1g commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            let current_urgency = user.urgency.unwrap_or(Urgency::VeryLow);
I've added a comment about the fallback. It uses VeryLow as a default because if the user doesn't set a minimum, it means they want all messages

2025-01-03 08:03 UTC, p1gp1g commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            if self.app_state.db.update_user(&mut user).await.is_ok() {
I have done it to return a 404 if the user isn't saved yet (if they send urgency before registering to a channel)

2025-01-03 08:04 UTC, p1gp1g commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +                200
Should I change something ?

2025-01-03 08:05 UTC, p1gp1g commented on autopush-common/src/db/mod.rs
> +}
I've added `From<Option<&String>>`

2025-01-07 17:13 UTC, jrconlin commented
Thanks! Looks good. I'm going to do a quick bit of research on the client code to see if there are any potential impacts, but I like the approach you took. 

Sigh, Also just noted that this commit is not signed, (see our [Contributing doc](https://github.com/mozilla-services/autopush-rs/blob/master/CONTRIBUTING.md#sending-pull-requests). I also just realized that we never linked to [what "sign" means](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-verification), which might explain a few things ( _sighs_ ). Unfortunately, we cannot land unsigned commits, so you will need to close this PR in favor of one that is signed, or once we get approval, we can resubmit this for you. My apologies for not catching that earlier.

2025-01-07 18:41 UTC, p1gp1g commented
I have signed the commits. Let me know how your tests go with the client, there shouldn't be any issue since the ServerMessage::Urgency is only send after a ClientMessage::Urgency

FYI, I've written a [UnifiedPush](https://unifiedpush.org/) (~webpush for mobile applications) distributor that uses autopush, and I did the tests with it. By the way, I'll try to add UnifiedPush support to Firefox-Android soon

2025-01-10 00:01 UTC, jrconlin commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            if self.app_state.db.update_user(&mut user).await.is_ok() {
The problem is that if `update_user(..)` fails, we ought to know why (e.g. there may be a database issue happening that we should track. If the update fails, we should record the error and pass back a result that's meaningful to the caller. That's mostly handled by the existing error processing, but `is_ok()` interrupts that.

Granted, having this function return a context free status `500` doesn't really help much either. (How did we get this? How do we fix the problem? etc.)

If we get a 500, I'd say that all bets are off and that we return a proper 500 that closes the connection. 

That leaves either a list of pending `ServerMessage`s, or a single `ServerMessage` with a 404 status. 

I'd probably do something like (the following is me just writing code. Please correct any glaring bugs):

```
if let Some(mut user) = self.app_state.db.get_user(&self.uaid).await? {
    // If the user hasn't set a minimum urgency yet, they receive all messages,
    // which is equivalent to setting very-low as a minimum
    let current_urgency = user.urgency.unwrap_or(Urgency::VeryLow);

    // We update the user
    user.urgency = Some(new_min);
    user.connected_at = ms_since_epoch();

    // if new urgency < previous: fetch pending messages
    self.app_state.db.update_user(&mut user).await?;

    let mut res = vec![ServerMessage::Urgency { status: actix_web::http::StatusCode::OK }];
    // if new urgency < previous: fetch pending messages
    if new_min < current_urgency {
          self.ack_state.unacked_stored_highest = None;
          self.current_timestamp = None;
          res.append(&mut self.check_storage().await?);
      }
      // We return the Urgency Ack + pending messages
      return Ok(res); 
} else {
      return Ok(vec![ServerMessage::Urgency { status: actix_web::http::StatusCode::NOT_FOUND }])
}
```

2025-01-10 09:05 UTC, p1gp1g commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            if self.app_state.db.update_user(&mut user).await.is_ok() {
OK I see, I've pushed a patch. Regarding the status code, I prefer not mixing types, all other `ServerMessage`'s status are `u32`, and I think they should migrated to `StatusCode` in the same time.

2025-01-10 16:18 UTC, jrconlin commented on autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
> +            if self.app_state.db.update_user(&mut user).await.is_ok() {
You're right. That was more me thinking out loud that we should be consistent about using `StatusCode` when possible, but that should _not_ be part of this PR.

2025-01-10 16:20 UTC, jrconlin approved these changes
I'm going to give one of the other dev's a chance to look this over before I land it.

Thank you for this!

2025-02-10 14:03 UTC, p1gp1g commented
@jrconlin For information, how much time do you give them to review it ?

2025-02-10 16:15 UTC, jrconlin commented
Well, there's an outstanding conflict in the PR right now, so it's not going to land until that's resolved. Since this is isolated anyway, I'll land it after that's done and I give it a quick re-review.

2025-02-10 17:44 UTC, p1gp1g commented
I have rebased the branch

2025-02-10 17:50 UTC, jrconlin approved these changes

2025-02-10 19:01 UTC, jrconlin commented
Sigh. Just noticed that these commits aren't signed. [We require all commits to be signed](https://github.com/mozilla-services/autopush-rs/blob/master/CONTRIBUTING.md#sending-pull-requests) before we can accept them. (I've tried to make that very clear in the docs and PR templates, but I guess there's still work to do)

Sadly, that means we can't accept this PR as is (even one unsigned commit corrupts things.)

You can either close this PR and resubmit it or I can submit it on your behalf, but I'll need one of the other core folk to sign off on it.

2025-02-11 12:56 UTC, p1gp1g commented
I have squashed the branch and signed the commit

2025-02-11 17:01 UTC, jrconlin approved these changes

2025-02-14 18:17 UTC, jrconlin commented
Closing this in favor of https://github.com/mozilla-services/autopush-rs/pull/841 because of CI and signature issues.

2025-02-14 18:17 UTC, closed without merging